name: Olaf-Neighbourhood Protocol App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libssl-dev zlib1g-dev

      - name: Cache CMake Build for JSON
        uses: actions/cache@v3
        with:
          path: json/build
          key: json-build-${{ hashFiles('json/CMakeLists.txt') }}
          restore-keys: |
            json-build-

      - name: Cache CMake Build for websocketpp
        uses: actions/cache@v3
        with:
          path: websocketpp/build
          key: websocketpp-build-${{ hashFiles('websocketpp/CMakeLists.txt') }}
          restore-keys: |
            websocketpp-build-

      - name: Pull C++ Libraries if Not Cached
        run: |
          if [ ! -d "json" ]; then
            git clone https://github.com/nlohmann/json
          fi
          if [ ! -d "websocketpp" ]; then
            git clone https://github.com/zaphoyd/websocketpp
          fi

      - name: Create Build Directories if Not Exist
        run: |
          mkdir -p json/build websocketpp/build

      - name: Build and Install JSON Dependency if Not Installed
        run: |
          if [ ! -f "/usr/local/include/nlohmann/json.hpp" ]; then
            cd json/build
            cmake ..
            sudo make install
          else
            echo "JSON library is already installed, skipping build."
          fi

      - name: Build and Install websocketpp Dependency if Not Installed
        run: |
          if [ ! -f "/usr/local/include/websocketpp/config.hpp" ]; then
            cd websocketpp/build
            cmake ..
            sudo make install
          else
            echo "websocketpp library is already installed, skipping build."
          fi

      - name: Run Makefile Test
        run: make test
