name: Olaf-Neighbourhood Protocol App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libssl-dev zlib1g-dev cmake

      - name: Pull C++ Libraries
        run: |
          git clone https://github.com/nlohmann/json
          git clone https://github.com/zaphoyd/websocketpp

      - name: Create Build Directories
        run: |
          mkdir -p json/build websocketpp/build

      - name: Build JSON Dependency
        working-directory: ${{github.workspace}}/json/build/
        run: |
          cmake ..
          cmake --build .

      - name: Build websocketpp Dependency
        working-directory: ${{github.workspace}}/websocketpp/build/
        run: |
          cmake ..
          cmake --build .

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true

      - name: Run Tests
        run: |
          cd build
          ctest
