name: Olaf-Neighbourhood Protocol App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libssl-dev zlib1g-dev

      - name: Cache JSON Library
        uses: actions/cache@v3
        with:
          path: json/build
          key: json-build-${{ hashFiles('json/CMakeLists.txt') }}
          restore-keys: |
            json-build-

      - name: Cache websocketpp Library
        uses: actions/cache@v3
        with:
          path: websocketpp/build
          key: websocketpp-build-${{ hashFiles('websocketpp/CMakeLists.txt') }}
          restore-keys: |
            websocketpp-build-

      - name: Pull C++ Libraries
        run: |
          git clone https://github.com/nlohmann/json
          git clone https://github.com/zaphoyd/websocketpp

      - name: Create Build Directories
        run: |
          mkdir -p json/build websocketpp/build

      - name: Build JSON Library
        working-directory: ${{github.workspace}}/json/build/
        run: |
          cmake ..
          make

      - name: Cache Built JSON Library
        uses: actions/cache@v3
        with:
          path: json/build
          key: json-build-${{ hashFiles('json/build') }}
          restore-keys: |
            json-build-

      - name: Install JSON Library
        working-directory: ${{github.workspace}}/json/build/
        run: sudo make install

      - name: Build websocketpp Library
        working-directory: ${{github.workspace}}/websocketpp/build/
        run: |
          cmake ..
          make

      - name: Cache Built websocketpp Library
        uses: actions/cache@v3
        with:
          path: websocketpp/build
          key: websocketpp-build-${{ hashFiles('websocketpp/build') }}
          restore-keys: |
            websocketpp-build-

      - name: Install websocketpp Library
        working-directory: ${{github.workspace}}/websocketpp/build/
        run: sudo make install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libssl-dev zlib1g-dev

      - name: Run Makefile Test
        run: make test
